[33m9f0b166[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m Fix: Eliminar carpeta scripts del repositorio para evitar errores de build
[33m7bfb313[m Fix: Eliminar menciones de consulta gratuita y sin compromiso - Reemplazar 'Consulta Gratuita' por 'Contáctanos' o 'Consulta' - Eliminar 'sin compromiso' de todas las descripciones - Actualizar traducciones en español e inglés - Corregir claves de traducción en Footer para servicios
[33m061e2fb[m Fix: Excluir carpeta scripts del build de Next.js - Agregar webpack config para ignorar scripts - Actualizar tsconfig.json para excluir scripts - Corregir error de compilación en AWS Amplify
[33m5a3d5bb[m Fix: Reemplazar icono Hospital por Building2 en página de ciudades - Hospital no existe en lucide-react - Usar Building2 que ya está importado
[33mea09aeb[m Feat: Añadir script de importación de posts desde CSV a Supabase - Procesa CSV con 3448 artículos - Distribuye publicaciones desde dic 2023 cada 2 semanas - Auto-publica posts con fecha <= hoy - Convierte Markdown a HTML - Genera slugs, excerpts y meta descriptions automáticamente - Calcula tiempo de lectura - Inserta en lotes de 50 para evitar timeouts - Modo de prueba incluido (sin insertar datos) - Documentación completa en scripts/README.md
[33m0e22a45[m Feat: Mejorar sustancialmente páginas de ciudades con contenido rico - Sección de servicios locales con iconos y enlaces - Sección de hospitales de la ciudad con datos de Supabase - Sección sobre sanidad local y contexto específico - Sección de proceso paso a paso adaptada a la ciudad - Sección de por qué elegirnos con 4 ventajas - FAQs locales visibles en accordion - Mejorado hero con mejor diseño y stats - Lazy initialization con getSupabaseAdmin() - Contenido específico para cada ciudad con más de 8 secciones - Mejor UX y diseño consistente con la home
[33m41fb375[m Feat: Añadir sitemap HTML con enlace en el footer - Creada página /sitemap con todas las páginas organizadas por categorías - Añadido enlace en el footer junto a páginas legales - Añadidas traducciones en español e inglés - Muestra páginas principales, servicios, ciudades, blog posts, noticias y páginas legales
[33m0b44488[m Fix: Lazy initialization de Supabase client en todas las rutas API - Evita errores durante el build cuando las variables de entorno no están disponibles - Creado helper getSupabaseAdmin() en lib/supabase/admin.ts - Actualizadas todas las rutas API para usar lazy initialization - Actualizado sitemap.ts para manejar errores de conexión durante el build
[33m0e35b55[m Fix: Corregir error de React Hook en Header - Mover useTranslations('services') fuera del callback del map - Ahora se llama al inicio del componente como debe ser
[33m8cc9cdb[m Fix: Eliminar bloque icons duplicado en layout de locale
